packages:
  - packages/plugins/vscode/*
  - packages/design-system/*

hoist: false
preferWorkspacePackages: true

publicHoistPattern:
  - '@storybook/react-vite'
overrides:
  serialize-javascript: ^7.0.5
allowBuilds:
  '@swc/core': true
  '@vscode/vsce-sign': true
  core-js: false
  esbuild: true
  keytar: false
